### ISSUE TITLE
cannot build with boost 1.71 

### ISSUE THREAD

**Issue by shirishag75** [rareylab/RingDecomposerLib#8]
Hi there, 

Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954351

and specifically this part - 

> Downloading https://github.com/rareylab/RingDecomposerLib/archive/v1.1.3_rdkit.tar.gz
> == Updating Filters.cpp from pains file
> == Done updating pains files
> -- Configuring done
> CMake Error at Code/cmake/Modules/RDKitUtils.cmake:153 (add_executable):
>   Target "testCoordGen" links to target "Boost::system" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> Call Stack (most recent call first):
>   External/CoordGen/CMakeLists.txt:110 (rdkit_test)

Can you fix it ?

**Comment by flachsenberg** [comment]
This error has nothing to do with the RingDecomposerLib. The RingDecomposerLib does not use boost at all and the error clearly occurs in the actual RDkit CMake files.

**Comment by shirishag75** [comment]
where would that come from ? the RDkit CMake files ?

**Comment by d-b-w** [comment]
Yeah. Would you mind reporting this to the RDKit issue tracker?

**Comment by shirishag75** [comment]
> Yeah. Would you mind reporting this to the RDKit issue tracker?

have no problem, need to know where the RDKIT issue tracker lies, need the URL, thank you.

**Comment by d-b-w** [comment]
sorry, of course: https://github.com/rdkit/rdkit/issues
